//! `help_markdown` — the Help virtual document's content (plan WP7.S1),
//! generated from the real binding tables so the Help doc and each pane's
//! own key handling can never drift apart: `## Global`/`## Leader`/
//! `## Explorer`/`## Open Tabs`/`## Editor` are each built by iterating
//! `keymap::GLOBAL_BINDINGS`/`global::LEADER_BINDINGS`/
//! `explorer_keys::EXPLORER_BINDINGS`/`opentabs::TABS_BINDINGS`/
//! `keymap::editor_bindings::EDITOR_BINDINGS` — the SAME tables
//! `footer::default_hint_spans` and each pane's `resolve_in` call already
//! read (one source of truth, `Binding::label`/`global::leader_label` the
//! shared display-string chokepoints).
//!
//! Plan WP6.S7 replaced the former hand-written `## Editor` section (the
//! one hand-maintained key list, kept in sync by hand with `keymap::
//! resolve`'s match arms) with this same reflection pass, once
//! `editor_bindings::EDITOR_BINDINGS` gave the editor's own chords a real
//! table to reflect over — CONSTITUTION §12: "a hand-maintained key list may
//! not exist".

use crate::explorer_keys::EXPLORER_BINDINGS;
use crate::global::{self, LEADER_BINDINGS};
use crate::keymap::editor_bindings::EDITOR_BINDINGS;
use crate::keymap::{Binding, GLOBAL_BINDINGS};
use crate::opentabs::TABS_BINDINGS;

/// Builds the whole Help document's markdown: a `# Help` heading, one
/// `| Key | Action |` table per real binding table.
pub fn help_markdown() -> String {
    let mut out = String::from("# Help\n\n");
    push_table_section(&mut out, "Global", GLOBAL_BINDINGS);
    push_leader_section(&mut out);
    push_table_section(&mut out, "Explorer", EXPLORER_BINDINGS);
    push_table_section(&mut out, "Open Tabs", TABS_BINDINGS);
    push_table_section(&mut out, "Editor", EDITOR_BINDINGS);
    out
}

/// One `## <title>` section with a two-column markdown table, one row per
/// `bindings` entry, key label first (`Binding::label` — the same helper
/// `footer.rs`'s default hints already reuse; not duplicated here).
fn push_table_section<C: Copy + 'static>(out: &mut String, title: &str, bindings: &[Binding<C>]) {
    out.push_str("## ");
    out.push_str(title);
    out.push_str("\n\n| Key | Action |\n| --- | --- |\n");
    for binding in bindings {
        out.push_str("| ");
        out.push_str(&binding.label());
        out.push_str(" | ");
        out.push_str(binding.help);
        out.push_str(" |\n");
    }
    out.push('\n');
}

/// The `## Leader` section: generated by reflection over
/// `global::LEADER_BINDINGS` (§12 forbids a hand-maintained key list) —
/// the same table the footer's default hints read. Its own small function
/// rather than a `push_table_section` call because the key column renders
/// through `global::leader_label` (the `␣X`-style label), not
/// `Binding::label`.
fn push_leader_section(out: &mut String) {
    out.push_str("## Leader\n\n| Key | Action |\n| --- | --- |\n");
    for binding in LEADER_BINDINGS {
        out.push_str("| ");
        out.push_str(&global::leader_label(binding));
        out.push_str(" | ");
        out.push_str(binding.help);
        out.push_str(" |\n");
    }
    out.push('\n');
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn generates_headings_for_every_section() {
        let md = help_markdown();
        assert!(md.starts_with("# Help\n"));
        for heading in [
            "## Global",
            "## Leader",
            "## Explorer",
            "## Open Tabs",
            "## Editor",
        ] {
            assert!(md.contains(heading), "missing {heading:?} in:\n{md}");
        }
    }

    #[test]
    fn every_global_binding_help_label_and_key_label_appears() {
        let md = help_markdown();
        for binding in GLOBAL_BINDINGS {
            assert!(
                md.contains(binding.help),
                "missing help label {:?}",
                binding.help
            );
            assert!(
                md.contains(&binding.label()),
                "missing key label {:?}",
                binding.label()
            );
        }
    }

    /// Regression: the Leader section is generated by reflection over
    /// `LEADER_BINDINGS`, not a hand-maintained list (§12) — every entry's
    /// help label and `␣`-prefixed key label must appear.
    #[test]
    fn every_leader_binding_help_label_and_key_label_appears() {
        let md = help_markdown();
        for binding in LEADER_BINDINGS {
            assert!(
                md.contains(binding.help),
                "missing leader help label {:?}",
                binding.help
            );
            assert!(
                md.contains(&global::leader_label(binding)),
                "missing leader key label {:?}",
                global::leader_label(binding)
            );
        }
    }

    /// Plan WP6 "Done when" gate: no hand-maintained editor key list left
    /// (see this module's doc comment), AND the generated `## Editor`
    /// section's row count equals `EDITOR_BINDINGS.len()` exactly —
    /// reflection, not a hand-authored count that could silently drift
    /// from the table.
    #[test]
    fn editor_section_row_count_matches_the_table() {
        let md = help_markdown();
        let section = md
            .split("## Editor\n\n")
            .nth(1)
            .expect("Editor section present");
        let row_count = section
            .lines()
            .filter(|line| {
                line.starts_with("| ") && *line != "| Key | Action |" && *line != "| --- | --- |"
            })
            .count();
        assert_eq!(row_count, EDITOR_BINDINGS.len());
    }

    /// Plan WP6 "Done when": the generated Help doc contains the reload
    /// binding — read straight off `EDITOR_BINDINGS` itself (via `editing::
    /// RELOAD`, the same constant `Command::Reload`'s dispatch arm binds),
    /// never a hardcoded `"reload image"`/`"⌘R"` literal, so a future
    /// rename of the help text or a rebind to a different chord can't
    /// silently leave this test asserting stale strings.
    #[test]
    fn the_reload_binding_appears_in_the_generated_help_doc() {
        let md = help_markdown();
        let reload = crate::keymap::editor_bindings::RELOAD;
        assert!(
            md.contains(reload.help),
            "missing reload help label {:?}",
            reload.help
        );
        assert!(
            md.contains(&reload.label()),
            "missing reload key label {:?}",
            reload.label()
        );
    }
}
