//! rune-tui: the Elm-style runtime, terminal lifecycle, keymap resolver, and
//! editor UI. Depends on rune-core and rune-md; owns the one place in the
//! workspace that talks to a real terminal (`term::Guard`).

pub mod app;
mod app_view;
pub mod binding;
pub(crate) mod breadcrumb;
pub(crate) mod breadcrumb_layout;
pub mod clipboard;
pub mod commands;
pub mod db;
pub mod db_ack;
mod db_dispatch;
pub mod db_enqueue;
mod db_types;
pub mod diff_view;
mod dispatch;
pub mod document;
pub(crate) mod document_map;
pub mod document_support;
mod editor_fast_path;
pub mod explorer;
pub(crate) mod explorer_dirload;
pub mod explorer_keys;
mod explorer_mouse;
pub(crate) mod explorer_preview;
pub mod explorer_reveal;
pub mod explorer_search;
pub(crate) mod field;
pub(crate) mod fileicons;
mod filesearch;
pub mod focus;
pub mod footer;
pub(crate) mod footer_hints;
pub(crate) mod footer_modes;
pub mod generation;
pub(crate) mod global;
pub mod graphics;
pub mod guard;
pub mod help;
pub mod highlight;
pub(crate) mod history_persistence;
pub mod keymap;
pub mod layout;
mod layout_column;
pub mod linemap;
pub(crate) mod listnav;
pub mod materialize_ack;
pub mod merge;
pub mod messages;
pub(crate) mod navhistory;
pub(crate) mod navigate;
pub mod opentabs;
pub(crate) mod fuzzymatch;
mod overlay;
mod palette;
pub mod pane;
mod pane_bar_policy;
mod pane_command;
mod pane_global;
mod pane_quit;
mod pane_refusal;
pub mod pointer;
pub(crate) mod queryline;
pub(crate) mod read_only;
pub(crate) mod region;
pub mod registry;
pub mod rename;
pub(crate) mod rename_create;
pub mod render;
pub mod row_meta;
pub mod runtime;
pub(crate) mod save;
mod search;
pub(crate) mod split;
pub(crate) mod term;
#[cfg(any(test, feature = "testgrid"))]
pub mod testgrid;
pub mod theme;
pub mod title;
pub(crate) mod trash;
pub mod undogroup;
pub mod viewport;
pub(crate) mod width;
pub mod workspace;
pub mod workspaceroot;
