[package]
name = "rune-tui"
version = "0.1.0"
edition.workspace = true

[dependencies]
rune-core = { path = "../rune-core" }
rune-md = { path = "../rune-md" }
ratatui = { workspace = true, features = ["termina"] }
ratatui-termina = { workspace = true }
termina = { workspace = true }
base64 = { workspace = true }

[dev-dependencies]
rune-core = { path = "../rune-core" }

[lints]
workspace = true
